//------------------------------------------------------------------------------
// <auto-generated>
// 			This code was generated by the tool.
// 			Runtime Version:4.0.30319.42000
//
// 			Changes to this file may cause incorrect behaviour and
// 			disappears if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aviator_Hack.Properties {
    using System;
    
    
    /// <summary>
    /// A resource class whose type is uniquely specified, for operations such as searching for localised strings.
    /// </summary>
    // This class is StronglyTypedResourceBuilder using a tool like ResGen or Visual Studio
    // automatically generated by the class.
    // To add or remove a member, edit your .ResX file, and then use ResGen command with the /str option or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Returns the cached instance of ResourceManager used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aviator_Hack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// Overrides the CurrentUICulture property of the current thread for all
        /// Overrides the CurrentUICulture property for all resource searches.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
